import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

const isProduction = process.env.NODE_ENV === 'production';

console.log(`Running migrations in ${isProduction ? 'production' : 'local'} mode...`);

try {
  const mainMigrationsDir = path.join('prisma', 'migrations');
    
  // Create migrations directory if it doesn't exist
  if (!fs.existsSync(mainMigrationsDir)) {
    fs.mkdirSync(mainMigrationsDir, { recursive: true });
    console.log('Created migrations directory');
  }
  if (isProduction) {
    // Production: Use Neon PostgreSQL
    console.log('1. Setting up PostgreSQL migrations...');
    
    // Clear existing migrations and copy PostgreSQL ones
    const postgresDir = path.join('prisma', 'postgres-migrations');
    
    
    // Remove existing migrations (but keep the directory structure)
    const existingDirs = fs.readdirSync(mainMigrationsDir);
    for (const dir of existingDirs) {
      const dirPath = path.join(mainMigrationsDir, dir);
      if (fs.statSync(dirPath).isDirectory()) {
        fs.rmSync(dirPath, { recursive: true, force: true });
        console.log(`Removed existing migration: ${dir}`);
      }
    }
    
    if (fs.existsSync(postgresDir)) {
      const postgresFiles = fs.readdirSync(postgresDir);
      
      for (const file of postgresFiles) {
        if (file.endsWith('.sql')) {
          const migrationName = path.parse(file).name;
          const sourceFile = path.join(postgresDir, file);
          const targetDir = path.join(mainMigrationsDir, migrationName);
          const targetFile = path.join(targetDir, 'migration.sql');
          
          // Create target directory
          if (!fs.existsSync(targetDir)) {
            fs.mkdirSync(targetDir, { recursive: true });
          }
          
          // Copy the migration file
          fs.copyFileSync(sourceFile, targetFile);
          console.log(`Copied PostgreSQL migration: ${migrationName}`);
        }
      }
    }
    
    // Create migration_lock.toml for PostgreSQL
    const migrationLockContent = `# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "postgresql"
`;
    fs.writeFileSync(path.join(mainMigrationsDir, 'migration_lock.toml'), migrationLockContent);
    console.log('Created PostgreSQL migration_lock.toml');
    
    console.log('2. Generating Prisma client...');
    execSync('npx prisma generate', { stdio: 'inherit' });
    
    console.log('3. Running PostgreSQL migrations...');
    execSync('npx prisma migrate deploy', { stdio: 'inherit' });
    
    console.log('4. Seeding production database...');
    execSync('npm run seed', { stdio: 'inherit' });
  } else {
    // Local: Use SQLite
    console.log('1. Setting up SQLite migrations...');
    
    // Clear existing migrations and copy SQLite ones
    const sqliteDir = path.join('prisma', 'sqlite-migrations');
    
    // Remove existing migrations (but keep the directory structure)
    const existingDirs = fs.readdirSync(mainMigrationsDir);
    for (const dir of existingDirs) {
      const dirPath = path.join(mainMigrationsDir, dir);
      if (fs.statSync(dirPath).isDirectory()) {
        fs.rmSync(dirPath, { recursive: true, force: true });
        console.log(`Removed existing migration: ${dir}`);
      }
    }
    
    if (fs.existsSync(sqliteDir)) {
      const sqliteFiles = fs.readdirSync(sqliteDir);
      
      for (const file of sqliteFiles) {
        if (file.endsWith('.sql')) {
          const migrationName = path.parse(file).name;
          const sourceFile = path.join(sqliteDir, file);
          const targetDir = path.join(mainMigrationsDir, migrationName);
          const targetFile = path.join(targetDir, 'migration.sql');
          
          // Create target directory
          if (!fs.existsSync(targetDir)) {
            fs.mkdirSync(targetDir, { recursive: true });
          }
          
          // Copy the migration file
          fs.copyFileSync(sourceFile, targetFile);
          console.log(`Copied SQLite migration: ${migrationName}`);
        }
      }
    }
    
    // Create migration_lock.toml for SQLite
    const migrationLockContent = `# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "sqlite"
`;
    fs.writeFileSync(path.join(mainMigrationsDir, 'migration_lock.toml'), migrationLockContent);
    console.log('Created SQLite migration_lock.toml');
    
    console.log('2. Generating Prisma client for SQLite...');
    execSync('npx prisma generate --schema=./prisma/schema.sqlite.prisma', { stdio: 'inherit' });
    
    console.log('3. Running SQLite migrations...');
    execSync('npx prisma migrate deploy --schema=./prisma/schema.sqlite.prisma', { stdio: 'inherit' });
    
    console.log('4. Seeding local database...');
    execSync('npm run seed', { stdio: 'inherit' });
  }
  
  console.log('✅ Migrations completed successfully!');
} catch (error) {
  console.error('❌ Migration failed:', error.message);
  process.exit(1);
}
